pluginManagement {
    repositories {
        maven {
            name = "repo.mleitz1.com"
            url = "https://repo.mleitz1.com/repository/dependencies-all/"
            credentials {
                username = nexusUsername
                password = nexusPassword
            }
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = "repo.mleitz1.com"
            url = "https://repo.mleitz1.com/repository/dependencies-all/"
            credentials {
                username = nexusUsername
                password = nexusPassword
            }
            mavenCentral()
        }
    }
}

rootProject.name = 'quarkus-build-helper-plugin'
